### ISSUE TITLE
hope for add markdown-it-container  plugin

### ISSUE THREAD

**Issue by shudibo** [qjebbs/vscode-markdown-extended#1]
This is a great extension of vscode! I hope you can add another plugin，markdown-it-container. 
Thank you!

**Comment by qjebbs** [comment]
OK. But it is not highly customizable, only supports DIV blocks with class specified, eg.:

Input:
```
::: warning
here be dragons
:::
```

Output:
```html
<div class="warning">
<p data-line="6" class="code-line">here be dragons</p>
</div>
```

You may change class name `warning` to whatever you want. 

Is that what you want?
