### ISSUE TITLE
PDF output character size does not match with preview window character size

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#11]
Preview window is centered and has pretty large character size, where PDF output is left aligned and have very small character size.

I saw that we can't scale up the PDF through settings, any idea how to fix this issue?

**Comment by qjebbs** [comment]
PS: I like export to html, then print to pdf in chrome, this make things under control.😀

**Comment by qjebbs** [comment]
See discussion there: https://github.com/ariya/phantomjs/issues/12685

set page size to A3 kind of solving the problem:

```
---
phantomjs:
    type: pdf
    format: A3
---
```

**Comment by cilerler** [comment]
Thanks for the prompt response.  

Issue I reported is opposite of the issue there.  Text should be larger not smaller and align does not match. I could change the paper size to A6 but it will affect the print size so that method is not a solution and very "unpleasant" workaround.

![bitmoji](https://render.bitstrips.com/v2/cpanel/def490d5-d6c4-433d-b32b-ce8faf14eb79-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)

> PS: I like export to html, then print to pdf in chrome, this make things under control.😀

I disagree on that, especially page breaks _(`<div style="page-break-after: always;">&nbsp;</div>`)_ become very difficult to manage when I try it through HTML

Also you may want to start using plugin that supports [puppeteer](https://developers.google.com/web/tools/puppeteer/) instead of PhantomJS

I tried extension called [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) and the result is pretty nice.  _(I'm going to update here with the screenshots of the difference in following minutes so you can see the differences)_

**Comment by cilerler** [comment]
I did not set no settings fyi

## original source preview

![image](https://user-images.githubusercontent.com/385958/40871265-85af6a1e-6606-11e8-80b2-57deb02fc5f5.png)

## markdown-extended
![image](https://user-images.githubusercontent.com/385958/40871275-a58dcfa6-6606-11e8-9f4a-10e647a410e0.png)

## markdown-pdf
![image](https://user-images.githubusercontent.com/385958/40871279-b0f134d2-6606-11e8-829a-42aa2c4049de.png)

**Comment by qjebbs** [comment]
Thanks for the info, I will look into it ASAP.

**Comment by qjebbs** [comment]
Switched to puppeteer, thanks for your information.

**Comment by cilerler** [comment]
@qjebbs I just tested it and it works great!

![bitmoji](https://render.bitstrips.com/v2/cpanel/ef534e16-69f9-4568-92e4-554ab1d99d40-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)
