### ISSUE TITLE
关于是否需要添加list 切换的命令探讨

### ISSUE THREAD

**Issue by heartacker** [qjebbs/vscode-markdown-extended#118]
插件添加了
- 切换有序列表
- 切换无需列表的命令。
两个命令。同事还占用了CTRL+L 这个快捷键。

快捷键冲突一直都是vscode 头疼的问题。尤其是和默认快捷键有冲突的，我是非常不赞同使用和默认快捷键一样的快捷键的。

不过在使用了一段时间后，我发现这个快捷键是很少用的，
相比常用的加粗，斜体等，列表切换反而是比较少的
作为一个 *文本* 编辑器。用户更多的可能还是使用手写的方式去创建一个列表。

输入`-` 创建一个列表。
输入`1. ` 创建一个有序列表。因为这是最简单和容易理解的markdown的方式。
我个人认为`ctrl+l `不但占用了会快捷键，还不一定让用户很好很方便的使用，同时也不一定能有很多用户会使用这个快捷键，

因此，我想，是否真的有必要添加这个默认的快捷键绑定

!!! 我的个人建议：
    删除切换有序无序列表的默认快捷键。同时减少快捷键冲突。

**Comment by qjebbs** [comment]
I tend to remove all default keybindings...
