### ISSUE TITLE
Markdown-it-admonition support

### ISSUE THREAD

**Issue by tramponi** [qjebbs/vscode-markdown-extended#12]
Could you add support for markdown admonitions? 

https://www.npmjs.com/package/markdown-it-admonition

**Comment by qjebbs** [comment]
Do you mean this?

**Comment by tramponi** [comment]
Yes, exactly.

**Comment by qjebbs** [comment]
Styles (css) needed, for `vscode-light`, `vscode-dark`, `vscode-high-contrast`.  Need some time on it, any pull requests are welcome.

**Comment by qjebbs** [comment]
added
