### ISSUE TITLE
Admonitions Fail to Display

### ISSUE THREAD

**Issue by jmanthony3** [qjebbs/vscode-markdown-extended#120]
Issue Type: <b>Bug</b>

After performing VS Code update this morning, none of the Markdown admonitions display properly within my Markdown notes for classes.

Extension version: 1.0.19
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.40GB free)|
|Process Argv|--crash-reporter-id d17dcf09-a9c2-4505-9b94-904b43e5d3ee|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Mutantpenguin** [comment]
Can confirm. Doesn't work with 1.62.

**Comment by Mutantpenguin** [comment]
Would love to help debug this but have no experience with TypeScript nor VSCode extensions.

Any pointers for me where to start?

**Comment by jmanthony3** [comment]
Can confirm that Markdown Preview Enhanced preview renders admonitions.

**Comment by alkisg** [comment]
I'm also affected by this, thank you all for reporting it and filing the PR.
