### ISSUE TITLE
Mangled markdown preview

### ISSUE THREAD

**Issue by oddnoc** [qjebbs/vscode-markdown-extended#125]
Issue Type: <b>Bug</b>

Markdown preview has reduplicated headings when the file changes.

Extension version: 1.1.0
VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|--crash-reporter-id dc6d2d55-ce1f-4990-82d0-f9d5dd5bad1c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Mutantpenguin** [comment]
Can confirm. Problem only occured to me after the update to VSCode 1.63.
