### ISSUE TITLE
markdownExtended.phantomPath hint as "Unknown configuration setting"

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#13]
I was updating settings and saw that the setting I added based on https://github.com/qjebbs/vscode-markdown-extended/issues/3 is hinting as "Unknown configuration setting"

```
"markdownExtended.phantomPath": "C:\\Program Files (x86)\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe",
```

However everything seems working fine, I just wanted to let you know.

**Comment by qjebbs** [comment]
According to our discussion https://github.com/qjebbs/vscode-markdown-extended/issues/11, `puppteer` is a better exporter, and does everything `phantomjs` does, so I removed `phantomjs`.

You can simply remove `"markdownExtended.phantomPath` in user setting, and even the `phantomjs` binary.

Thanks again for your feedback.
