### ISSUE TITLE
support markdown-it-plantuml

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#14]
I use [PlantUML](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) and code below in Markdown file. 

I can see the content in preview window if I allow insecure-content without any problem.  

However exporting to PDF is not working.  I'm not 100% sure but hoping that [markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml) may solve the problem.

````
```plantuml
 @startuml
 alice->bob:hello
 @enduml
```
````

**Comment by qjebbs** [comment]
Thanks for feedback, the exporter didn't wait for the resources.
