### ISSUE TITLE
what is the default path of the downloaded chromium exec?

### ISSUE THREAD

**Issue by goyalyashpal** [qjebbs/vscode-markdown-extended#151]

**Comment by hybras** [comment]
Downloaded extensions are availible under ~/.vscode (or ~/.vscode-oss if using vscodium).

It'll be something like

~/.vscode/.../jebs-md-extended.../node_modules/pupetter/..../Chrome

**Comment by goyalyashpal** [comment]
got it :) thanks a lot. 

----

note to self: adding some more context for myself: 
to get computer to spit the extensions folder itself is. command palette: "Extensions: Open Extensions Folder" 
which for windows is similar to unix one: `%USERPROFILE%/.vscode-oss/extensions`

thereafter: seriously; don't use MS explorer. just use doublecmd to highlight by letter & navigate to above mentioned directory (while considering the directory size)

`jebbs.markdown-extended-1.1.3-universal\node_modules\puppeteer\.local-chromium\`

it's a bit unfortunate for me that _most all_ (870MiB out of 885MiB) of the space required by this extension is consumed by just these browsers....

![image](https://github.com/qjebbs/vscode-markdown-extended/assets/19423063/527fcd77-18ea-4ccd-bba3-551784033747)

**Comment by goyalyashpal** [comment]
i really wish there was some way that there was one common extension for `puppeteer` which all other extensions could refer to as a dependency.

* but i think i have read somewhere (prolly in this extension itself) that the pptr it fetches is tested for it or smth like...
* which i think would mean that different extensions _may_ require different versions of pptr; 
* which _can_ result in multiple pptr being downloaded anyway

but i think it will still be worth giving it a try to guage for potential space and bandwidth saving; as there are 2-3 at least pdf or markdown rendering extensions which might be downloading their own pptr simultaneously
