### ISSUE TITLE
Markdown-it-admonition trims first character of the type when title exists

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#16]
### Output

![image](https://user-images.githubusercontent.com/385958/41290234-3af32c7e-6e1a-11e8-9103-ce333f5d70d6.png)

### Code block for easy testing
```
!!! note
This is the admonition body

!!!

!!! note This is the admonition title
This is the admonition body

!!!

!!! hint This is the admonition title
This is the admonition body
!!!

!!! attention This is the admonition title
This is the admonition body

!!!

!!! caution This is the admonition title
This is the admonition body

!!!

!!! danger This is the admonition title
This is the admonition body

!!!

!!! error This is the admonition title
This is the admonition body

!!!
```

**Comment by qjebbs** [comment]
Yes, I found this problem, but we should wait https://github.com/docarys/markdown-it-admonition/issues/5 to fix this. Similarly, we have another issue https://github.com/docarys/markdown-it-admonition/issues/4

**Comment by cilerler** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9ab32e9a-f43b-4dd4-90f6-1c4c77b47655-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)
