### ISSUE TITLE
Export does not if no folder is opened in VSCode

### ISSUE THREAD

**Issue by paulbombarde** [qjebbs/vscode-markdown-extended#19]
Hello,

Since previous Code update (1.24.0), the export to file does not work anymore, whatever the format. Still ko after full reinstall of VSCode (1.25.0) with only markdown-extended extension freshly installed.

I tried setting the puppeteer executable path without luck. Other similar extensions (Markdown to pdf) that also rely on puppeteer do work correctly (but do not support all the same feature you do).

I'm on win10. Is there any debug info I can get to see what happening ?
Best regards,
Paul

**Comment by paulbombarde** [comment]
No error messages. The pop-up appears, with the running indicatior spinning under for a less than a second, then the pop-up disappear silently. No extra pop-up for success or failure.

There is no out directory created either. I tried to create it before running the export, but no luck.

**Comment by qjebbs** [comment]
cannot reproduce, works good here 1.25.0 on win10

**Comment by paulbombarde** [comment]
I tested with one of my collegue and he has the same issue. That may be linked to the windows 10 set up from our IT...

Do you have an idea on how to debug this ? I never touch VSCode extension code...

**Comment by qjebbs** [comment]
You told that export doesn't work for any formats, but I guess it works at least for `html`, since html export doesn't rely on puppeteer.

**Comment by paulbombarde** [comment]
It does not work either for html. That really strange. I'm trying a quick debug session.

**Comment by paulbombarde** [comment]
Got it : I don't always open folders in VSCode, especially when I want to quickly generate a pdf from a md file : I have configured windows to open md file in VSCode.

In [export.js l.30](https://github.com/qjebbs/vscode-markdown-extended/blob/master/src/services/exporter/export.ts#L30) : 

```js
    if (!vscode.workspace.workspaceFolders) { return []; }
```

If I open a folder before launching the export, everything is ok.

**Comment by qjebbs** [comment]
Thanks! It's my mistake, please update.

**Comment by paulbombarde** [comment]
If you want, I'll send a PR next week. Just tell me.

**Comment by paulbombarde** [comment]
Ok, I saw this update. :+1

**Comment by paulbombarde** [comment]
Correction confirmed. Thanks a lot !
