### ISSUE TITLE
markdown-it-plantuml support

### ISSUE THREAD

**Issue by b4456609** [qjebbs/vscode-markdown-extended#20]
Could you add support for markdown-it-plantuml?

https://github.com/gmunguia/markdown-it-plantuml

**Comment by qjebbs** [comment]
Install this extension [PlantUML](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml), you'll get what you want, and more capability editing PlantUML.

**Comment by b4456609** [comment]
Thank you. I can export markdown including PlantUML with extension PlantUML.
