### ISSUE TITLE
Error format with CJK characters

### ISSUE THREAD

**Issue by FourLeafTec** [qjebbs/vscode-markdown-extended#22]
Now it's error format with width character,Such as Chinese

Now it is like this:
![now](https://user-images.githubusercontent.com/5875432/46591639-95db3b00-caee-11e8-9298-9789502d6e15.PNG)

One Chinese character is twice as width as English character.
So the right will be like this:
![right](https://user-images.githubusercontent.com/5875432/46591714-32054200-caef-11e8-8528-eb71a0f0e494.PNG)

**Comment by qjebbs** [comment]
Can you share your font for testing?

**Comment by qjebbs** [comment]
Thanks, tested good with your font, closing..
