### ISSUE TITLE
mermaid support

### ISSUE THREAD

**Issue by itelite2006** [qjebbs/vscode-markdown-extended#23]
能否支持 mermaid 导出呢？

**Comment by qjebbs** [comment]
1. Update to markdown extended latest
2. Install [markdown-mermaid](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid)

Enjoy!

**Comment by itelite2006** [comment]
That's awesome! Thanks @qjebbs!

**Comment by goyalyashpal** [comment]
hi! the export of markdown-mermaid to pdf is still not working for me. it's still showing the source code in the output pdf.

i am on vscodium v1.77.3 (non-latest) , [bierner.markdown-mermaid] v1.81.1 and [jebbs.markdown-extended] v1.1.3

[bierner.markdown-mermaid]: https://open-vsx.org/vscode/item?itemName=bierner.markdown-mermaid
[jebbs.markdown-extended]: https://open-vsx.org/vscode/item?itemName=jebbs.markdown-extended

### minimum working example

````markdown
```mermaid
---
title: Sample Mermaid
---
%%{ init: {
    'theme': 'light', 
    'flowchart': {'curve': 'linear', 'defaultRenderer': 'elk'}
    } }%%
graph TD
A(Forest) --> B[/Another/]
A --> C[End]
  subgraph section
  B
  C
  end
```

List:
* Markdown list item 1
* Item 5: Code comes from [mermaid-directives](https://mermaid.js.org/config/directives.html#directive-examples)

New Paragraph starts here.
````


### what i get
![image](https://github.com/qjebbs/vscode-markdown-extended/assets/19423063/d79b74e7-ada1-459c-b0e0-7ebfb3539238)

### expected:
![image](https://github.com/qjebbs/vscode-markdown-extended/assets/19423063/ddf670cb-6a79-4d67-8eb5-89db7732b9c9)
