### ISSUE TITLE
Not to suppress blank lines in blockquote

### ISSUE THREAD

**Issue by cangyuyao** [qjebbs/vscode-markdown-extended#24]
The blockquote function triggered by Ctrl + Shift +Q removes blank lines in the selected content and suppresses everything in one paragraph. I'd like to keep the blank lines to separate different paragraphs. 
```
aaa

bb
```
Current result:
```
> aaa
> bb
```
Expected result: 
```
> aaa
> 
> bb
```

**Comment by qjebbs** [comment]
please update
