### ISSUE TITLE
Support for tabs?

### ISSUE THREAD

**Issue by Yzrsah** [qjebbs/vscode-markdown-extended#29]
Have you ever seen any kind of markdown-it addon that allows support for tabs?

Like this:

```
Something
	Another
		Nesting
	Another

This type of hierarchy is very common
	Across multiple domains
```

Which would render with a nice custom style for the tabulation.

Great extension and thanks.

**Comment by Yzrsah** [comment]
@qjebbs here is a small demonstration
![Indentation](https://i.imgur.com/aeDOTUL.png)

**Comment by Yzrsah** [comment]
@qjebbs here is a small demonstration

![indentation](https://i.imgur.com/cnZ7zoi.png)

**Comment by qjebbs** [comment]
MarkdownIt use `tab` or 4 space indent to identify blocks, it's the specification, I cannot change, or bring in some conflict syntaxes. Further, It's `MarkdownIt`'s decision to make, if anyone want bring new grammar into the specification. 

Currently, To indent in rendered lines, use list:

```
- aaaaaa
    - aaaaaa
    - aaaaaa
- bbbbbb
    - bbbbbb
    - bbbbbb
```

- aaaaaa
    - aaaaaa
    - aaaaaa
- bbbbbb
    - bbbbbb
    - bbbbbb

 To align columns like tab does in traditional writing, use table:

```
Q. What's your choice?

| A. 11111 | B. 2|
|:-|:-|
| C. 3 | D. 44444|
```

Q. What's your choice?

| A. 11111 | B. 2|
|:-|:-|
| C. 3 | D. 44444|

If you don't want the list style `dot` or the table border line, it a matter of the style sheet you use.

Anyway, it out of the scope of the extension development, I just give some advices according to my experience.

**Comment by Yzrsah** [comment]
The main idea:

- Indentation **without** using `-` and `*`
We do not want `-` and `*`
We do not want to add modify all things and insert thousands of `-` and `*` all over, where it is inappropriate

- Indentation **without** table
We do not want to insert complex table writing

We want to use **tabs**

**Comment by Yzrsah** [comment]
The main idea:

- Indentation **without** using `-` and `*`
We do not want `-` and `*`
We do not want to add modify all things and insert thousands of `-` and `*` all over, where it is inappropriate

- Indentation **without** table
We do not want to insert complex table writing

We want to use **tabs only**
Table ruins the document

**Comment by Yzrsah** [comment]
The main idea:

- Indentation **without** using `-` and `*`
We do not want `-` and `*`
We do not want to add and insert thousands of `-` and `*` all over, where it is inappropriate

- Indentation **without** table
We do not want to insert complex table writing all over thousands of lines

We want to use **tabs only**
Table destroys the document

**Comment by Yzrsah** [comment]
The main idea:

- Indentation **without** `-` and `*`
We do not want `-` and `*`
We do not want to add and insert thousands of `-` and `*` all over, where it is inappropriate

- Indentation **without** table
We do not want to insert complex table writing all over thousands of lines

We want to use **tabs only**
Table destroys the document

We like innovations and new ideas, not the old traditional ideas

**Comment by qjebbs** [comment]
Those are only my personal suggestions.

Sounds like you want to add new grammar to [MarkdownIt](https://github.com/markdown-it/markdown-it) or [new plugin for MarkdownIt](https://www.npmjs.com/search?q=keywords:markdown-it-plugin) for your situation, but they're all out of scope of this extension development. This extension just integrates MarkdownIt and its plugins, to let VSCode users preview and export as `WYSIWYG`, not to change the MarkdownIt project or create new plugins.

If you had an idea (consider how to work with the `tab indent block` specification without conflict) to create a new plugin, or found relative existing plugins, I would be glad to integrate.

**Comment by Yzrsah** [comment]
Thank you qjebbs.

I will make plugin for tab indent block, when I have time
