### ISSUE TITLE
Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#3]
added `"markdownExtended.phantomPath": "C:\\Program Files (x86)\\phantomjs-2.1.1-windows\\bin"` into the **User Settings**

then followed steps below

1. <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>P</kbd>
2. `Markdown: Export to...` + <kbd>ENTER</kbd>
3. `PDF` + <kbd>ENTER</kbd>

and got 

```
ERROR Cannot read property 'render' of undefined
```

**Comment by qjebbs** [comment]
This is because you didn't trigger markdown preview window, that this plugin cannot get the render object.

**Comment by cilerler** [comment]
I appreciate if you may provide more details.  _(I have the preview screen right next to the code)_

Also it is not always throwing that exact error, most of the time either that error or error below.

![image](https://user-images.githubusercontent.com/385958/34671680-7c8c9f9e-f449-11e7-908a-99e871e823c5.png)

But it is consistent.  It either shows 1st one or 2nd one.

However when I receive `ERROR: write EPIPE` message when I 

1. open **User Settings** _(do nothing)_
2. and right after that try to export to `HTML` instead of `PDF, JPG, PNG` it works.  

But when I

1. export to `PDF` and receive the error 
2. then try to export `HTML` I receive exactly same error.

If I go back to **User Settings** and try to do export `HTML` it works again

**Comment by qjebbs** [comment]
I guess the problem could be the phantomPath setting, which should be full path of exe file. eg:

`C:\\Program Files (x86)\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe`

Can you try this?

**Comment by cilerler** [comment]
Thanks @qjebbs it did work. 🤗
