### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Rajpratik71** [qjebbs/vscode-markdown-extended#30]
- Issue Type: `Performance`
- Extension Name: `markdown-extended`
- Extension Version: `1.0.3`
- OS Version: `Linux x64 4.15.0-24-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/reddragon/jebbs.markdown-extended-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Rajpratik71** [comment]
it is in my linux home folder i.e. "/home/reddragon/" .

As , i pasted the log below

**Comment by qjebbs** [comment]
Sorry, I don't see the `/home/reddragon/jebbs.markdown-extended-unresponsive.cpuprofile.txt`, that nothing I can do now.

**Comment by Rajpratik71** [comment]
> Sorry, I don't see the `/home/reddragon/jebbs.markdown-extended-unresponsive.cpuprofile.txt`, that nothing I can do now.

here is the log i uploaded it to github gist 

[https://gist.github.com/Rajpratik71/5eb25479f99cb5c1f7e59d0a4325fd65]
