### ISSUE TITLE
Incorrect `[` nested crash

### ISSUE THREAD

**Issue by XYShaoKang** [qjebbs/vscode-markdown-extended#32]
- Issue Type: error
- Extension Name: markdown-extended
- Extension Version: 1.0.3
- OS Version: win10 1803 x64
- VSCode version: 1.30.1

When `[` error nesting, vscode gets stuck and reports an error

To reproduce :
  1. Enable markdown-extended
  2. Create a new MD file
  3. Enter or paste `test [[text]`
  4. Program jammed
  5. A hint later `Extension host terminated unexpectedly. `
  6. Disable markdown-extended
  7. Retry steps 2 - 3 without errors

Error in console output
![2018-12-26_4-22-33](https://user-images.githubusercontent.com/38753204/50426325-1297dd00-08c6-11e9-8152-152cbcdea5b3.jpg)

I found the same problem in another win10 and Linux (manjaro).

I think it's probably related to markdown-extension. If I'm wrong, please let me know.

I think when the format is wrong, you can send a prompt, or log output, instead of causing vscode to die.

I'm not very proficient in debugging vscode extensions, so I can't get more information. I'd be happy if I could help.

English is not my native language; please excuse typing errors.

Thanks

**Comment by qjebbs** [comment]
It was  a bug of `markdown-it-kbd`, which is fixed here: 
https://github.com/jGleitz/markdown-it-kbd/commit/0610fd405dba7c58c8cdcb036d704d053b9b55af

I'll update the dependency, thanks for report!
