### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by royki** [qjebbs/vscode-markdown-extended#36]
- Issue Type: `Performance`
- Extension Name: `markdown-extended`
- Extension Version: `1.0.5`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/croy/jebbs.markdown-extended-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by qjebbs** [comment]
duplicated with #41
