### ISSUE TITLE
Request: Include Support for the <mark> tag

### ISSUE THREAD

**Issue by JackDMF** [qjebbs/vscode-markdown-extended#38]
Please include support for the mark plugin of markdownit
It can be found here:
https://github.com/markdown-it/markdown-it-mark

It adds support for the html5 <mark> tag by using double == as markup.

Thank you a lot for this extension!

**Comment by qjebbs** [comment]
Thanks, please update.

**Comment by qjebbs** [comment]
PS: You can press <kbd>ctrl+m</kbd> to toggle mark.

**Comment by JackDMF** [comment]
Thanks a lot! This addition is very much appreciated!
