### ISSUE TITLE
Add support for markdown-it-emoji

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#39]
Would you please add support for [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji)

Thanks in advance 🤗 

![image](https://user-images.githubusercontent.com/385958/54615098-e3f85100-4a33-11e9-9c91-e251280f5bf5.png)

**Comment by qjebbs** [comment]
Please use a existing extension, [Markdown Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji). The extension can work with other markdown extensions well, both preview and export.

Same solution if you like [Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath), [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) and others.

**Comment by cilerler** [comment]
I hear you, and I saw that part in the README before I post this issue.
However, I'm asking only for **Emoji** and not the rest.

My reasoning is, this extension covers all the features in https://markdown-it.github.io/ except the **Emoji**. And I understand that you don't want it to be a "generic" solution but there is a clear path here, anything exists in markdown-it demo should be covered by extension, rest should be getting done by other extensions.

Would you mind reconsider it, please?

Thank you very much for your time and attention.

**Comment by qjebbs** [comment]
Added, please update

**Comment by cilerler** [comment]
Thank you very much, you may also want to update **Markdown Extension Pack** since it does use **Markdown Emoji** and not letting me uninstall it.  Again, thank you for reconsidering it. 🤗
