### ISSUE TITLE
Export does not work on VS 1.21.1

### ISSUE THREAD

**Issue by paulbombarde** [qjebbs/vscode-markdown-extended#4]
Hello,

With VS code version 1.21.1, the export function is down : the panel to specify the export format doesn't appear anymore. Seems linked to new notification mechanism.

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Regards,
Paul

**Comment by qjebbs** [comment]
Is there any error message showed? I test good with 1.21.0 on mac

**Comment by paulbombarde** [comment]
Hello,

No error message. I'm under windows (tested 7/10/server 2012). Everything worked correctly before.

 I also have issues with the GitHub preview extension. It has windows specific issues too, see https://github.com/mjbvz/vscode-github-markdown-preview-style/issues/17

Regards
Paul

**Comment by qjebbs** [comment]
Thanks for the information, seems we have to wait for 1.21.1 to resolve this.

**Comment by paulbombarde** [comment]
I tried one silly thing : uninstall the extension, stop VSCode, reinstall the extension, reload. It now works as usual. The github styling is still not taken into acount in the preview window, but the pdf rendering is ok, with the github style.

Issue closed for me. Sorry for the inconvience.
Thanks a lot for your great tools (I heavily use your PlantUML extension).

**Comment by qjebbs** [comment]
Good to hear. You are welcome.
