### ISSUE TITLE
Incorrect image path when working in folder or workspace

### ISSUE THREAD

**Issue by mykoza** [qjebbs/vscode-markdown-extended#40]
Hi,

I have a problem with local images (works from web) not showing in exported documents. It doesn't matter if I provide relative or absolute path to an image. I searched through previous issues, it maybe similar to #7.

When working on a file with path `main_folder/folder1/doc.md` and image in the same folder, the export by default is created in `main_folder/out/folder1/doc.html` with path to image in html set to `folder1/image.jpg`, and that's why it doesn't show up.

If I change Export Dir setting to `./` the html is created in the same folder as md, which is nice, but image path in html is still `folder1/image.jpg`, so it doesn't work either.

If I write full path to image in markdown, for example: `![Photo](C:/.../main_folder/folder1/image.jpg)`, image path is set to `folder1/C:/.../main_folder/folder1/image.jpg`.

Am I doing something wrong or is it a bug?

Thanks!

**Comment by qjebbs** [comment]
Shouldn't be...The extension export html self-contained, user don't have to care about the image location, because it's base64 encoded and embedded in to the file.

**Comment by mykoza** [comment]
Just to be sure, the command is `Markdown: Export to  File`, right?
Well, I'm just saying what the extension does for me, maybe it's something on my end, but if I use another extension (Markdown All in One) it does encode images to base64.

**Comment by qjebbs** [comment]
Yes, and the menu should be:

**Comment by mykoza** [comment]
Yep, exactly. So what's happening?

**Comment by qjebbs** [comment]
I guess you don't open the project folder, but only one of the file, in VSCode

**Comment by mykoza** [comment]
Sorry, but I'm sure I have a folder open. I even made a workspace end added a folder, just to check. Same result.

**Comment by qjebbs** [comment]
As I look into the code, I guess (again..) you may have special character in you folder name or path. This is a bug I will fix before next release.

**Comment by qjebbs** [comment]
Can you confirm if remove special characters solve your problem or not? Thanks!

**Comment by mykoza** [comment]
Ok, I made a sample folder in `C:\Folder\Subfolder\doc.md` and `image.png` and it does work!

Is `space` a special character?

**Comment by qjebbs** [comment]
Yes, I should have fixed the issue with the latest commit. Thanks for all your information

**Comment by mykoza** [comment]
No problem, I should thank you for quick fix.
