### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by VBs7** [qjebbs/vscode-markdown-extended#45]
[jebbs.markdown-extended-unresponsive.cpuprofile.txt](https://github.com/qjebbs/vscode-markdown-extended/files/3093879/jebbs.markdown-extended-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `markdown-extended`
- Extension Version: `1.0.8`
- OS Version: `Linux ia32 4.4.0-144-generic`
- VSCode version: `1.32.3`

**Comment by qjebbs** [comment]
Tracking with #41
