### ISSUE TITLE
markdown-it-container is not working

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#5]
All others are working perfectly however *markdown-it-container* is not.

Used the code below 

```
::::: container
:::: row
::: col-xs-6 alert alert-success
success text
:::
::: col-xs-6 alert alert-warning
warning text
:::
::::
:::::
```

Saw `Rendered with style bootstrap)` in the document but couldn't be sure  if it means I have to do something to make it work.

**Comment by qjebbs** [comment]
Yes, you have to config user setting like this to make the demo work:

```json
"markdown.styles": [
        "path/to/bootStrapStyle.css"
]
```

**Comment by qjebbs** [comment]
According to the document, the css should be placed in current workspace: [View Here](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css).

The css path can also be a URL, it works when preview, but not export which provided by this plugin. I will update in next release.

**Comment by qjebbs** [comment]
user styles are supported with v0.2.1, please update, and configure:

```json
"markdown.styles": [
    "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
]
```

Or

```json
"markdown.styles": [
    "styles/bootstrap.min.css"
]
```
The export result will also be as expected.

**Comment by cilerler** [comment]
I appreciate for all your help.  Thank you!
