### ISSUE TITLE
PDF export does not include content

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#56]
Suddenly PDF export is not working. 

- [Output](https://github.com/qjebbs/vscode-markdown-extended/files/3547242/201935_DevOps.pdf) shows file-name, page number, date, etc. but no content. 
- However, PNG is working fine.
- Last time I did be able to create PDF was last Tuesday.  
- I did uninstall and install the extension, and it did re-downloaded Chrome.

How can I troubleshoot it?  Thanks in advance.

**Comment by qjebbs** [comment]
Cannot reproduce, works good here on Mac.

**Comment by cilerler** [comment]
It looks like https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack is causing it, FYI

**Comment by qjebbs** [comment]
Yes, it's a bug introduced by `docs-preview` extension.

**Comment by cilerler** [comment]
I appreciate for follow-up, thank you very much!
