### ISSUE TITLE
Unusual shortcut for move columns

### ISSUE THREAD

**Issue by henningBunk** [qjebbs/vscode-markdown-extended#59]
Hi there,
awesome plugin. Only one small gripe with it. I seldom move my cursor letter by letter but jump word by word by pressing `Option`+`←` or `Option`+`→` (on mac).
When I am editing markdown and there are tables, this commo, system wide shortcut isn't working anymore because it gets overriden by the extension shortcut to move a column left or right.
Can I change the keyboard settings of the extension somehow? If not, can the shortcut be changed to something which isnt already in use by the OS?

Cheers!

**Comment by qjebbs** [comment]
I'm changing the default keyboard shortcuts for `move columns`, according to #57. But any way, user can change any key bindings with VSCode `Preference: Open Keyboard Shortcuts`.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/16953333/65384743-6998e880-dd58-11e9-853a-11c80e961051.png">

**Comment by henningBunk** [comment]
thanks for the answer the hint how to change shortcuts. didnt found it myself. i will close this issue since its a duplicate.

**Comment by jLouzado** [comment]
@qjebbs has this change been published already?

Generally yes people can just delete the shortcut, but if it's breaking something basic like word-navigation then I would hesitate to recommend the plugin widely to my team even though the plugin as a whole is amazing. 

Thank you for making the change. 🙏
