### ISSUE TITLE
Blocks Markdown preview on 1.22.1

### ISSUE THREAD

**Issue by paulbombarde** [qjebbs/vscode-markdown-extended#6]
Hello,

On latest release version, the extension does not launch correctly (it seems) and it block the Markdown preview window.

To reproduce :

1. install VS Code 1.22.1,
2. install extension
3. Open a md file
4. Launch 'open preview to the side (Ctrl+K V)'
5. Wait...

You'll get a "Extension host terminated unexpectedly." error message. In developper tools, I get the following stack :

```
[Extension Host] debugger inspector at %c

#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#

==== C stack trace ===============================


/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2774 [Extension Host] debugger inspector at %c	v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString [0x000007FEE309145B+178411]
	V8_Fatal [0x000007FEE2D7039D+125]
	v8::SharedArrayBuffer::Externalize [0x000007FEE2CF4789+937]
	v8::internal::Builtins::WasmStackGuard [0x000007FEE30E4895+82149]
	v8::internal::AllocationSpaceName [0x000007FEE30F1928+53352]
	v8::internal::Builtins::WasmStackGuard [0x000007FEE30DFA5C+62124]
	v8::internal::AllocationSpaceName [0x000007FEE30E7D56+13462]
	v8::internal::AllocationSpaceName [0x000007FEE30EFB16+45654]
	GetHandleVerifier [0x000000013F91A1B7+740567]
	RtlDllShutdownInProgress [0x0000000077B2D13B+843]
	DbgUiRemoteBreakin [0x0000000077C19E87+1863]
	BaseThreadInitThunk [0x0000000077A159CD+13]
	RtlUserThreadStart [0x0000000077B7383D+29]

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2857 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
w._onExtensionHostCrashed @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2857

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217 Extension host terminated unexpectedly.
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217
```

Version info:
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T02:26:57.615Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Regards,
Paul

**Comment by qjebbs** [comment]
Cannot reproduce. The error message has nothing obviously suggests that it's a problem caused by this plugin.

Maybe it is some kind of conflict. Can you disable all other plugins, to make sure this issue happens again?

**Comment by paulbombarde** [comment]
I did exactly to this:

1. disabled all plugins, no issue in preview. 2. Enabled md extended only, I got this error after a pretty long wait ~1 min and no preview.
3. Disabled md extended, re enable all other extensions, including plantuml and GitHub styling, preview work correctly
4. Enabled all extensions, preview is not working.

I forgot to precise that I'm under windows. The issue appeared after last automatic update of vs code.

**Comment by qjebbs** [comment]
I tested with 1.22.1 in win10, still cannot reproduce. Can it be the incomplete installation? How about reinstall the plugin, or even the Code?

**Comment by paulbombarde** [comment]
Hello,

I uninstalled the extension completely, restarted code (not reload, but real restart), reinstalled the extension, reloaded code and the issue is fixed. It seems that the reload after uninstall did not completely cleaned up the previous install.

Still a weird issue from VSCode...
Sorry the noise.
Thanks again for your various extensions !

**Comment by qjebbs** [comment]
Good news, you're welcome!
