### ISSUE TITLE
It can not show admonition when use markdown preview enhanced plugin?

### ISSUE THREAD

**Issue by ragcatshxu** [qjebbs/vscode-markdown-extended#62]
I install vscode-markdown-extended,and then install Markdown Preview Enhanced too.
when preview the md file, I found the admonition can not show , can anyone give some suggestion?

**Comment by qjebbs** [comment]
No of course. Markdown Preview Enhanced is not designed to work with other extensions, and nothing can be done from here.

PS: Don't use preview command of MPE, but the built-in one, you'll see the admonition.
