### ISSUE TITLE
Toggle Ordered Lists not auto-incrementing, each line repeats "1."

### ISSUE THREAD

**Issue by datocrats-org** [qjebbs/vscode-markdown-extended#63]
The Markdown: Toggle Ordered List is making each line start with 1.  instead of 1. 2. 3. etc. in the raw.  Rendered is ok.

**Unformatted (input, selecting all three lines)**
Line 1 
Line 2
Line 3

**Formatted (output) repeats 1. in each line but renders correctly**
1. Line 1
1. Line 2
1. Line 3

**Expected both in text and rendering**
1. Line 1
2. Line 2
3. Line 3

This plugin's capability to toggle numbered list is working as of this posting: Name: Markdown Shortcuts
Id: mdickin.markdown-shortcuts
Description: Shortcuts for Markdown editing
Version: 0.11.0
Publisher: mdickin
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts

**Comment by qjebbs** [comment]
This is expected. The number doesn't matter for ordered list, even:

```
1. A
8. B
6. C
```

will rendered in correct order:

1. A
8. B
6. C

Numbering with all `1.` is better when you try change line orders sometimes

**Comment by datocrats-org** [comment]
my view is the auto numbering of raw markdown would be helpful, a possible improvement over the default. closing
