### ISSUE TITLE
When Rendered with style bootstrap, puppeteer landscape wront work

### ISSUE THREAD

**Issue by leandro-costa** [qjebbs/vscode-markdown-extended#66]
when a add 

"markdown.styles": [
    "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
]

landscape in pdf  wront work

**Comment by qjebbs** [comment]
Then you need to be responsible for what you do. It's about `bootstrap+Chromium PDF` problem, not the extension.

**Comment by leandro-costa** [comment]
Ok, you may want to remove the README.md bootstrap suggestion, or warn that there are incompatibilities
