### ISSUE TITLE
Sometimes plantuml diagram doesn't export to PDF

### ISSUE THREAD

**Issue by leandro-costa** [qjebbs/vscode-markdown-extended#67]
I did some tests with the  [file](https://raw.githubusercontent.com/ifbasaj/markdown_presentation_vscode/master/AulaCollections.md) and the diagram did not export to PDF.

I changed "page.setContent" for "page.goto" to a temporary file on "puppeteer.ts" and it worked

[commit](https://github.com/leandro-costa/vscode-markdown-extended/commit/3f0d83cf0083ed2d446d877db754af8196824d1e)

**Comment by qjebbs** [comment]
Cannot reproduce, I test with the same file you provided, and it exported OK.

Use a tmp file will increase unnecessary disk writing, that is what I always try to avoid.

**Comment by leandro-costa** [comment]
Can you test with [This file](https://raw.githubusercontent.com/ifbasaj/markdown_presentation_vscode/master/MarkdownExtended.md) and :

> {"plantuml.server": "https://www.plantuml.com/plantuml"}

?

**Comment by qjebbs** [comment]
Puppeteer waits until the network request is idle, but  the [PLantUML](https://github.com/qjebbs/vscode-plantuml) renders diagram with `object` tag, which is not count as a request of current document, I guess. I'll revert this commit: https://github.com/qjebbs/vscode-plantuml/commit/7d8548559d83e05c6059de64dbece0af9797f7e9 later.

No change is required with this extension.
