### ISSUE TITLE
Request: Add Markdown-it-imsize like handling?

### ISSUE THREAD

**Issue by Pmeholm** [qjebbs/vscode-markdown-extended#75]
Hi, 
Is there a possibilty of adding some sort of handling of imagesize?

I know that some platforms support it, and some don't, and even the handling is pretty different, but this could probably be defined and even turned on/off in config?

https://www.npmjs.com/package/@centerforopenscience/markdown-it-imsize

**Comment by qjebbs** [comment]
Just install this:

<https://marketplace.visualstudio.com/items?itemName=amoosbr.markdown-imsize>

See also [Why You Don't Integrate Some Plugin?](https://github.com/qjebbs/vscode-markdown-extended#q-why-you-dont-integrate-some-plugin)
