### ISSUE TITLE
tocLevels not recognised correctly

### ISSUE THREAD

**Issue by mbunyan** [qjebbs/vscode-markdown-extended#76]
The default for TOC markdown-it-table-of-contents displays a TOC with 1,2 & 3 headings.

When changing requirement to TOC with only level 2 and 3, the output is only level 3.

The VSCode settings, "markdownExtended.tocLevels": [2,3], is not being correctly interpreted.

Have tried setting at VSCode Workspace and global user setting. Both fail.

Any suggestions welcome please.
Mike B

**Comment by qjebbs** [comment]
Restart VSCode is required for this setting.
