### ISSUE TITLE
Plugin request: markdown-it-imsize

### ISSUE THREAD

**Issue by tw-space** [qjebbs/vscode-markdown-extended#82]
Would love support for plugin [markdown-it-imsize](https://github.com/tatsy/markdown-it-imsize).

The plugin enables setting an image's dimensions inline in simple syntax:

```md
![my image](./path/to/image.png =200x80)
```

translates to:

```html
<p><img src="./path/to/image.png" alt="my image" width="200" height="80"></p>
```

**Comment by qjebbs** [comment]
Install this one: https://marketplace.visualstudio.com/items?itemName=amoosbr.markdown-imsize

**Comment by Mutantpenguin** [comment]
The integrated functionality is not enough for you?

`![my image](./path/to/image.png){width="40pt"} `
`![my image](./path/to/image.png){width="100%"} `
`![my image](./path/to/image.png){width="60px"}  {align="center"}`

**Comment by tw-space** [comment]
@Mutantpenguin That... works. Amazing. I hadn't realized markdown(-it) supports inline style syntax. Mindblowing, thank you.
