### ISSUE TITLE
How to customize the font style of the exported html file

### ISSUE THREAD

**Issue by NGPONG** [qjebbs/vscode-markdown-extended#84]
Whether it is in my editor or preview, the font used is **Microsoft Yahei**, but the font style of the exported file does not know what it is. So how can i customize the font style of the exported html file, is there any options be set?

**Comment by qjebbs** [comment]
You were actually asking how to customize the markdown style: 

https://stackoverflow.com/questions/32410064/how-can-i-use-an-online-style-css-on-the-visual-studio-code-markdown-preview

Do what ever you want, since it's a WYSIWYG exporter.

**Comment by NGPONG** [comment]
> You were actually asking how to customize the markdown style:
> 
> https://stackoverflow.com/questions/32410064/how-can-i-use-an-online-style-css-on-the-visual-studio-code-markdown-preview
> 
> Do what ever you want, since it's a WYSIWYG exporter.

This works for me, tks!

**Comment by NGPONG** [comment]
solved
