### ISSUE TITLE
Disabling data-line and  class="code-line" ?

### ISSUE THREAD

**Issue by ragat69** [qjebbs/vscode-markdown-extended#85]
Hi,
Quick question as I like this plugin for the ability to "Copy HTML" quickly :
Is there a way to remove the **data-line** and **code-line** markup in the pasted html ? Like shown in the output below :
`<p data-line="0" class="code-line">text</p>`

I love all the functionnality offered in the copy markdown/pasting as html in this plugin but just can't seem to figure out how to get rid of this markup that I do not need.

Thanks in advance.

**Comment by qjebbs** [comment]
This behavior is added by VSCode team, not me, I cannot reach this part. Unless some write codes to parse output string, and remove the attributes.

While it doesn't do bad to common usage, I choose not to spend more time, since we are all busy.

**Comment by ragat69** [comment]
Thanks for the quick and efficient answer, no worries then !
