### ISSUE TITLE
Enter key not working in .md files

### ISSUE THREAD

**Issue by nashthecoder** [qjebbs/vscode-markdown-extended#93]
Issue Type: <b>Bug</b>

command 'markdown.extension.onEnterKey' not found

Extension version: 1.0.18
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.53GB free)|
|Process Argv|. --crash-reporter-id 32570675-da96-43ef-bce6-8da0052ea94d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by qjebbs** [comment]
Note that my extension id is `jebbs.markdown-extended`, `markdown.extension` is another one
