### ISSUE TITLE
Grid table disables outline view

### ISSUE THREAD

**Issue by khalid-hussain** [qjebbs/vscode-markdown-extended#99]
Using grid tables disables the showing of the outline view. Upon removal, everything goes back to normal.

![table](https://user-images.githubusercontent.com/3102714/112706997-0a82d980-8ee3-11eb-80f1-e93d85f0a034.gif)

**Comment by qjebbs** [comment]
this extension has nothing to do with outlining

**Comment by khalid-hussain** [comment]
Please double check if you can replicate this behavior or if it's not creating any issues for you.

**Comment by qjebbs** [comment]
You can check it by removing this extension, to see if the issue has gone or not
